services:
  db:
    image: mysql:latest
    container_name: mysql-compose-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  mql_networks: