spring.application.name=Music_Tracker
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# spring.datasource.name=musicDB
# spring.datasource.username=password
# spring.datasource.password=myuser

spring.jpa.hibernate.ddl=autoupdate
spring.sql.init.mode=always